[package]
name = "rk_boot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
clap-num = "1.0.2"
env_logger = "0.11.5"
log = "0.4.22"

async-io = "2.4.0"
futures-lite = { version = "2", default-features = false }
nusb = "=0.1.12"
